using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using TinadecCore.Abstractions.Ports;
using TinadecCore.DmaEA;
using TinadecCore.Lifecycle;
using TinadecCore.Models;
using TinadecCore.Persistence;
using TinadecCore.Prompts;

namespace TinadecCore.Runtime;

public sealed class ControlPlaneService
{
    private readonly IDbContextFactory<ModelControlDbContext> _models;
    private readonly IDbContextFactory<PromptControlDbContext> _prompts;
    private readonly IDbContextFactory<AgentControlDbContext> _agents;
    private readonly IDbContextFactory<LifecycleDbContext> _lifecycle;
    private readonly IContentStore _content;
    private readonly ISecretStore _secrets;
    private readonly ITenantContextAccessor _tenant;

    public ControlPlaneService(IDbContextFactory<ModelControlDbContext> models, IDbContextFactory<PromptControlDbContext> prompts,
        IDbContextFactory<AgentControlDbContext> agents, IDbContextFactory<LifecycleDbContext> lifecycle,
        IContentStore content, ISecretStore secrets, ITenantContextAccessor tenant)
    { _models = models; _prompts = prompts; _agents = agents; _lifecycle = lifecycle; _content = content; _secrets = secrets; _tenant = tenant; }

    private TenantContext Tenant => _tenant.Current;
    private static async Task<(string text, ContentReference reference)> PutJsonAsync(IContentStore store, Guid tenant, Guid? workspace, string kind, object value, CancellationToken ct)
    { var text = JsonSerializer.Serialize(value); await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(text)); return (text, await store.PutAsync(new ContentWriteRequest(tenant, workspace, kind, "application/json", stream), ct)); }
    private static async Task<string> ReadAsync(IContentStore store, string reference, CancellationToken ct)
    { await using var stream = await store.OpenReadAsync(new ContentReference(reference, "", 0, "application/json"), ct); using var reader = new StreamReader(stream); return await reader.ReadToEndAsync(ct); }
    private static bool Matches(long revision, string? match) => string.IsNullOrWhiteSpace(match) || long.TryParse(match, out var value) && value == revision;

    public async Task<IResult> ListProviders(CancellationToken ct)
    { await using var db = await _models.CreateDbContextAsync(ct); var rows = await db.Providers.Where(x => x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null).ToListAsync(ct); return Results.Ok(await Task.WhenAll(rows.Select(ToProvider))); }
    private async Task<object> ToProvider(ModelProviderRecord row)
    { await using var db = await _models.CreateDbContextAsync(); var version = await db.ProviderVersions.SingleOrDefaultAsync(x => x.Id == row.CurrentVersionId); Dictionary<string, JsonElement>? cfg = null; if (version != null) cfg = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(await ReadAsync(_content, version.ContentReference, default));
        JsonElement Value(string key) => cfg != null && cfg.TryGetValue(key, out var v) ? v : default;
        string? String(string key) => Value(key).ValueKind == JsonValueKind.String ? Value(key).GetString() : null;
        return new { id = row.Id, driver = row.Driver, display_name = row.DisplayName, connection_kind = row.ConnectionKind, base_url = String("base_url"), model = String("model"), has_api_key = row.SecretReference != null && _secrets.ExistsAsync(row.SecretReference).GetAwaiter().GetResult(), binary_path = String("binary_path"), home_path = String("home_path"), server_url = String("server_url"), launch_args = String("launch_args"), capabilities = cfg != null && cfg.TryGetValue("capabilities", out var c) && c.ValueKind == JsonValueKind.Array ? c.EnumerateArray().Select(x => x.GetString() ?? "").ToArray() : Array.Empty<string>(), enabled = row.Enabled, status = row.Enabled ? "configured" : "disabled", status_message = "Persisted configuration", revision = row.Revision, scope = row.Scope, created_at = row.CreatedAt, updated_at = row.UpdatedAt }; }

    public async Task<IResult> SaveProvider(JsonElement input, Guid? id, string? ifMatch, CancellationToken ct)
    { var now = DateTimeOffset.UtcNow; await using var db = await _models.CreateDbContextAsync(ct); var row = id.HasValue ? await db.Providers.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct) : null; if (row != null && !Matches(row.Revision, ifMatch)) return Results.StatusCode(412); if (row?.Id is null) { row = new ModelProviderRecord { Id = id ?? Guid.NewGuid(), TenantId = Tenant.TenantId, WorkspaceId = Tenant.WorkspaceId, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now, Revision = 0 }; db.Providers.Add(row); }
        row.Driver = input.TryGetProperty("driver", out var p) ? p.GetString() ?? "" : row.Driver; row.DisplayName = input.TryGetProperty("display_name", out p) ? p.GetString() ?? row.Driver : row.DisplayName; row.ConnectionKind = input.TryGetProperty("connection_kind", out p) ? p.GetString() ?? "api-key" : row.ConnectionKind; row.Scope = input.TryGetProperty("scope", out p) ? p.GetString() ?? "workspace" : row.Scope; row.Enabled = !input.TryGetProperty("enabled", out p) || p.ValueKind != JsonValueKind.False; row.UpdatedByPrincipalId = Tenant.PrincipalId; row.UpdatedAt = now;
        if (input.TryGetProperty("api_key", out p) && p.ValueKind == JsonValueKind.String && !string.IsNullOrEmpty(p.GetString())) { row.SecretReference ??= "provider-" + row.Id.ToString("N"); await _secrets.PutAsync(row.SecretReference, p.GetString()!, ct); } else if (input.TryGetProperty("clear_api_key", out p) && p.ValueKind == JsonValueKind.True && row.SecretReference != null) { await _secrets.DeleteAsync(row.SecretReference, ct); row.SecretReference = null; }
        var cfg = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(input.GetRawText()) ?? new(); var stored = await PutJsonAsync(_content, Tenant.TenantId, Tenant.WorkspaceId, "model-config", cfg, ct); var version = new ModelProviderVersionRecord { Id = Guid.NewGuid(), ProviderId = row.Id, Version = (int)row.Revision + 1, ContentReference = stored.reference.Value, ContentHash = stored.reference.Sha256, ContentLength = stored.reference.Length, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; row.Revision++; row.CurrentVersionId = version.Id; db.ProviderVersions.Add(version); await db.SaveChangesAsync(ct); return Results.Ok(await ToProvider(row)); }
    public async Task<IResult> DeleteProvider(Guid id, string? ifMatch, CancellationToken ct)
    { await using var db = await _models.CreateDbContextAsync(ct); var row = await db.Providers.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct); if (row == null) return Results.NotFound(); if (!Matches(row.Revision, ifMatch)) return Results.StatusCode(412); row.DeletedAt = DateTimeOffset.UtcNow; row.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.NoContent(); }
    public async Task<IResult> ListRoutes(CancellationToken ct)
    { await using var db = await _models.CreateDbContextAsync(ct); var rows = await db.Routes.Where(x => x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null).ToListAsync(ct); var output = new List<object>(); foreach (var row in rows) { var v = await db.RouteVersions.SingleAsync(x => x.Id == row.CurrentVersionId, ct); output.Add(new { purpose = row.Purpose, provider_instance_id = v.ProviderId, model = v.Model, revision = row.Revision, updated_at = row.UpdatedAt }); } return Results.Ok(output); }
    public async Task<IResult> SaveRoute(string purpose, JsonElement input, string? ifMatch, CancellationToken ct)
    { if (!input.TryGetProperty("provider_instance_id", out var provider) || !Guid.TryParse(provider.GetString(), out var providerId)) return Results.BadRequest(new { message = "provider_instance_id is required" }); await using var db = await _models.CreateDbContextAsync(ct); var row = await db.Routes.SingleOrDefaultAsync(x => x.Purpose == purpose && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct); var now = DateTimeOffset.UtcNow; if (row != null && !Matches(row.Revision, ifMatch)) return Results.StatusCode(412); if (row == null) { row = new ModelRouteRecord { Id = Guid.NewGuid(), TenantId = Tenant.TenantId, WorkspaceId = Tenant.WorkspaceId, Purpose = purpose, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; db.Routes.Add(row); } var version = new ModelRouteVersionRecord { Id = Guid.NewGuid(), RouteId = row.Id, Version = (int)row.Revision + 1, ProviderId = providerId, Model = input.TryGetProperty("model", out var m) ? m.GetString() : null, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; row.Revision++; row.CurrentVersionId = version.Id; row.UpdatedByPrincipalId = Tenant.PrincipalId; row.UpdatedAt = now; db.RouteVersions.Add(version); await db.SaveChangesAsync(ct); return Results.Ok(new { purpose = row.Purpose, provider_instance_id = version.ProviderId, model = version.Model, revision = row.Revision, updated_at = row.UpdatedAt }); }

    public async Task<IResult> ListPrompts(CancellationToken ct)
    { await using var db = await _prompts.CreateDbContextAsync(ct); var rows = await db.Fragments.Where(x => x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null).ToListAsync(ct); var output = new List<object>(); foreach (var row in rows) { await using var d = await _prompts.CreateDbContextAsync(ct); var v = await d.Versions.SingleAsync(x => x.Id == row.CurrentVersionId, ct); output.Add(new { id = row.Id, key = row.Key, title = row.Title, scope = row.Scope, target_agent_id = row.TargetAgentId, category = row.Category, content = await ReadAsync(_content, v.ContentReference, ct), priority = row.Priority, enabled = row.Enabled, is_builtin = row.IsBuiltIn, revision = row.Revision, created_at = row.CreatedAt, updated_at = row.UpdatedAt }); } return Results.Ok(output); }
    public async Task<IResult> SavePrompt(JsonElement input, Guid? id, string? ifMatch, CancellationToken ct)
    { await using var db = await _prompts.CreateDbContextAsync(ct); var now = DateTimeOffset.UtcNow; var row = id.HasValue ? await db.Fragments.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct) : null; if (row?.IsBuiltIn == true) return Results.Conflict(new { message = "Built-in prompt fragments are read-only." }); if (row != null && !Matches(row.Revision, ifMatch)) return Results.StatusCode(412); if (row == null) { row = new PromptFragmentRecord { Id = id ?? Guid.NewGuid(), TenantId = Tenant.TenantId, WorkspaceId = Tenant.WorkspaceId, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; db.Fragments.Add(row); } string Get(string n, string fallback = "") => input.TryGetProperty(n, out var p) ? p.GetString() ?? fallback : fallback; row.Key = Get("key", row.Key); row.Title = Get("title", row.Title); row.Scope = Get("scope", row.Scope); row.Category = Get("category", row.Category); row.Priority = input.TryGetProperty("priority", out var pr) ? pr.GetInt32() : row.Priority; row.Enabled = !input.TryGetProperty("enabled", out var en) || en.ValueKind != JsonValueKind.False; if (input.TryGetProperty("target_agent_id", out var ta) && Guid.TryParse(ta.GetString(), out var aid)) row.TargetAgentId = aid; var content = Get("content"); var stored = await PutJsonAsync(_content, Tenant.TenantId, Tenant.WorkspaceId, "prompt-fragment", content, ct); var version = new PromptFragmentVersionRecord { Id = Guid.NewGuid(), FragmentId = row.Id, Version = (int)row.Revision + 1, ContentReference = stored.reference.Value, ContentHash = stored.reference.Sha256, ContentLength = stored.reference.Length, ChangeSummary = "configuration update", CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; row.Revision++; row.CurrentVersionId = version.Id; row.UpdatedByPrincipalId = Tenant.PrincipalId; row.UpdatedAt = now; db.Versions.Add(version); await db.SaveChangesAsync(ct); return Results.Ok(new { id = row.Id, key = row.Key, title = row.Title, scope = row.Scope, target_agent_id = row.TargetAgentId, category = row.Category, content, priority = row.Priority, enabled = row.Enabled, is_builtin = row.IsBuiltIn, revision = row.Revision, created_at = row.CreatedAt, updated_at = row.UpdatedAt }); }
    public async Task<IResult> DeletePrompt(Guid id, CancellationToken ct) { await using var db = await _prompts.CreateDbContextAsync(ct); var row = await db.Fragments.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct); if (row == null) return Results.NotFound(); if (row.IsBuiltIn) return Results.Conflict(new { message = "Built-in prompt fragments are read-only." }); row.DeletedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.NoContent(); }

    public async Task<IResult> ListAgents(CancellationToken ct)
    { await using var db = await _agents.CreateDbContextAsync(ct); var rows = await db.Agents.Where(x => x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null).ToListAsync(ct); var result = new List<object>(); foreach (var row in rows) { await using var d = await _agents.CreateDbContextAsync(ct); var v = await d.Versions.SingleAsync(x => x.Id == row.CurrentVersionId, ct); var body = JsonSerializer.Deserialize<JsonElement>(await ReadAsync(_content, v.ContentReference, ct)); result.Add(new { id = row.Id, name = row.Name, layer = row.Layer, agent_type = row.AgentType, mode = body.TryGetProperty("mode", out var mode) ? mode.GetString() : "", description = body.TryGetProperty("description", out var desc) ? desc.GetString() : "", model_route_purpose = body.TryGetProperty("model_route_purpose", out var route) ? route.GetString() : "", allowed_tools = body.TryGetProperty("allowed_tools", out var tools) ? tools : JsonSerializer.SerializeToElement(Array.Empty<string>()), capabilities = body.TryGetProperty("capabilities", out var caps) ? caps : JsonSerializer.SerializeToElement(Array.Empty<string>()), system_prompt = body.TryGetProperty("system_prompt", out var prompt) ? prompt.GetString() : null, enabled = row.Enabled, is_built_in = row.IsBuiltIn, revision = row.Revision, updated_at = row.UpdatedAt }); } return Results.Ok(result); }
    public async Task<IResult> SaveAgent(Guid id, JsonElement input, string? ifMatch, CancellationToken ct)
    { await using var db = await _agents.CreateDbContextAsync(ct); var row = await db.Agents.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId && x.DeletedAt == null, ct); if (row?.IsBuiltIn == true) return Results.Conflict(new { message = "Built-in agents are read-only; clone them first." }); var now = DateTimeOffset.UtcNow; if (row != null && !Matches(row.Revision, ifMatch)) return Results.StatusCode(412); if (row == null) { row = new AgentProfileRecord { Id = id, TenantId = Tenant.TenantId, WorkspaceId = Tenant.WorkspaceId, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; db.Agents.Add(row); } row.Name = input.TryGetProperty("name", out var n) ? n.GetString() ?? row.Name : row.Name; row.Layer = input.TryGetProperty("layer", out var l) ? l.GetString() ?? row.Layer : row.Layer; row.AgentType = input.TryGetProperty("agent_type", out var t) ? t.GetString() ?? row.AgentType : row.AgentType; row.Enabled = !input.TryGetProperty("enabled", out var e) || e.ValueKind != JsonValueKind.False; var stored = await PutJsonAsync(_content, Tenant.TenantId, Tenant.WorkspaceId, "agent-profile", input, ct); var version = new AgentProfileVersionRecord { Id = Guid.NewGuid(), AgentId = row.Id, Version = (int)row.Revision + 1, ContentReference = stored.reference.Value, ContentHash = stored.reference.Sha256, ContentLength = stored.reference.Length, CreatedByPrincipalId = Tenant.PrincipalId, CreatedAt = now }; row.Revision++; row.CurrentVersionId = version.Id; row.UpdatedByPrincipalId = Tenant.PrincipalId; row.UpdatedAt = now; db.Versions.Add(version); await db.SaveChangesAsync(ct); return Results.Ok(new { id = row.Id, name = row.Name, layer = row.Layer, agent_type = row.AgentType, mode = input.TryGetProperty("mode", out var mode) ? mode.GetString() : "", description = input.TryGetProperty("description", out var description) ? description.GetString() : "", model_route_purpose = input.TryGetProperty("model_route_purpose", out var route) ? route.GetString() : "", allowed_tools = input.TryGetProperty("allowed_tools", out var tools) ? tools : JsonSerializer.SerializeToElement(Array.Empty<string>()), capabilities = input.TryGetProperty("capabilities", out var capabilities) ? capabilities : JsonSerializer.SerializeToElement(Array.Empty<string>()), system_prompt = input.TryGetProperty("system_prompt", out var prompt) ? prompt.GetString() : null, enabled = row.Enabled, is_built_in = row.IsBuiltIn, revision = row.Revision, updated_at = row.UpdatedAt }); }

    public async Task<IResult> ListApprovals(string? status, CancellationToken ct) { await using var db = await _lifecycle.CreateDbContextAsync(ct); var q = db.ApprovalRequests.Where(x => x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId); if (!string.IsNullOrWhiteSpace(status)) q = q.Where(x => x.Status == status); return Results.Ok(await q.OrderByDescending(x => x.CreatedAt).Select(x => new { id = x.Id, session_id = x.SessionId, kind = x.Kind, tool_id = x.ToolId, summary = x.Summary, status = x.Status, request_hash = x.RequestHash, expires_at = x.ExpiresAt, created_at = x.CreatedAt, updated_at = x.UpdatedAt }).ToListAsync(ct)); }
    public async Task<IResult> CreateApproval(JsonElement input, CancellationToken ct) { var now = DateTimeOffset.UtcNow; await using var db = await _lifecycle.CreateDbContextAsync(ct); var row = new ApprovalRequestRecord { Id = Guid.NewGuid(), TenantId = Tenant.TenantId, WorkspaceId = Tenant.WorkspaceId, SessionId = input.TryGetProperty("session_id", out var s) && Guid.TryParse(s.GetString(), out var sid) ? sid : null, Kind = input.TryGetProperty("kind", out var k) ? k.GetString() ?? "legacy" : "legacy", ToolId = input.TryGetProperty("tool_id", out var tool) ? tool.GetString() ?? "" : "", Summary = input.TryGetProperty("summary", out var sm) ? sm.GetString() ?? "" : "", RequestHash = input.TryGetProperty("request_hash", out var h) ? h.GetString() ?? "" : "", Status = "pending", ExpiresAt = now.AddMinutes(30), RequestedByPrincipalId = Tenant.PrincipalId, CreatedAt = now, UpdatedAt = now }; db.ApprovalRequests.Add(row); await db.SaveChangesAsync(ct); return Results.Ok(new { id = row.Id, session_id = row.SessionId, kind = row.Kind, summary = row.Summary, status = row.Status, created_at = row.CreatedAt }); }
    public async Task<IResult> DecideApproval(Guid id, JsonElement input, CancellationToken ct) { await using var db = await _lifecycle.CreateDbContextAsync(ct); var row = await db.ApprovalRequests.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == Tenant.TenantId && x.WorkspaceId == Tenant.WorkspaceId, ct); if (row == null) return Results.NotFound(); if (row.Status != "pending" || row.ExpiresAt <= DateTimeOffset.UtcNow) return Results.Conflict(new { message = "Approval is no longer actionable." }); var decision = input.TryGetProperty("decision", out var d) ? d.GetString() : null; if (decision is not ("approved" or "rejected")) return Results.BadRequest(new { message = "decision must be approved or rejected" }); row.Status = decision; row.UpdatedAt = DateTimeOffset.UtcNow; db.ApprovalDecisions.Add(new ApprovalDecisionRecord { Id = Guid.NewGuid(), ApprovalRequestId = id, Decision = decision, Reason = input.TryGetProperty("reason", out var reason) ? reason.GetString() : null, DecidedByPrincipalId = Tenant.PrincipalId, CreatedAt = row.UpdatedAt }); await db.SaveChangesAsync(ct); return Results.Ok(new { id = row.Id, status = row.Status, decided_at = row.UpdatedAt }); }
}
