import { defineComponent } from 'vue'
import {
  ArrowLeft,
  Bot,
  Check,
  ChevronRight,
  Circle,
  Cpu,
  Database,
  Download,
  Dna,
  Edit3,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  Info,
  KeyRound,
  LayoutGrid,
  List,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Palette,
  PanelRight,
  PawPrint,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings2,
  ShieldCheck,
  Square,
  Sun,
  Terminal,
  Trash2,
  Workflow,
  X,
} from '@lucide/vue'
import BrandLogo from '@/components/BrandLogo.vue'
import PetPreview from '@/components/PetPreview.vue'
import AgentTopologyCanvas from '@/components/AgentTopologyCanvas.vue'
import AgentEvolutionPanel from '@/components/AgentEvolutionPanel.vue'
import PromptEngineeringPanel from '@/components/PromptEngineeringPanel.vue'
import BackgroundPreview from '@/components/ui/background-preview.vue'
import PanelStyleControl from '@/components/ui/panel-style-control.vue'
import {
  UiBadge,
  UiButton,
  UiCard,
  UiDropdownMenu,
  UiInput,
  UiLabel,
  UiSkeleton,
  UiSwitch,
} from '@/components/ui'
import { useSettingsModuleContext } from './settingsModuleContext'

const settingsModuleComponents = {
  ArrowLeft,
  Bot,
  Check,
  ChevronRight,
  Circle,
  Cpu,
  Database,
  Download,
  Dna,
  Edit3,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  Info,
  KeyRound,
  LayoutGrid,
  List,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Palette,
  PanelRight,
  PawPrint,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings2,
  ShieldCheck,
  Square,
  Sun,
  Terminal,
  Trash2,
  Workflow,
  X,
  BrandLogo,
  PetPreview,
  AgentTopologyCanvas,
  AgentEvolutionPanel,
  PromptEngineeringPanel,
  BackgroundPreview,
  PanelStyleControl,
  UiBadge,
  UiButton,
  UiCard,
  UiDropdownMenu,
  UiInput,
  UiLabel,
  UiSkeleton,
  UiSwitch,
}

export function defineSettingsModule(name: string) {
  return defineComponent({
    name,
    components: settingsModuleComponents,
    setup() {
      return useSettingsModuleContext()
    },
  })
}
